---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: telemetry-release
- name: bosh-cli-github-release
- name: version

outputs:
- name: release-tarball

run:
  path: telemetry-release/ci/tasks/create-release.sh
