---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
  - name: telemetry-release

run:
  path: telemetry-release/ci/tasks/run-telemetry-receiver-tests.sh
