---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ruby
    tag: latest

inputs:
  - name: telemetry-release
  - name: ci

run:
  path: ci/ci/tasks/run-centralizer-unit-tests.sh
