---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ruby
    tag: latest

inputs:
  - name: telemetry-release

run:
  path: telemetry-release/ci/tasks/run-centralizer-unit-tests.sh
