---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ruby
    tag: latest

inputs:
  - name: bbl-state
  - name: bosh-cli-github-release
  - name: bbl-cli-github-release
  - name: telemetry-components-release

run:
  path: telemetry-components-release/ci/tasks/test-acceptance-sends-to-centralizer.sh
