---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ruby
    tag: latest

inputs:
  - name: bbl-state
  - name: bosh-cli-github-release
  - name: bbl-cli-github-release
  - name: telemetry-release

run:
  path: telemetry-release/ci/tasks/test-acceptance-sends-to-centralizer.sh

params:
  LOADER_URL:
  LOADER_API_KEY:
  CENTRALIZER_BOSH_DEPLOYMENT:
  AGENT_BOSH_DEPLOYMENT:
  EXPECTED_ENV_TYPE:
  EXPECTED_IAAS_TYPE:
  EXPECTED_FOUNDATION_ID:
